### ISSUE TITLE
Add a ReportType for Harassment

### ISSUE THREAD

**Issue by ctrlcctrlv** [abusix/xarf#34]
Same justification as #33.

**Comment by FrederikP** [comment]
Hi Fredrick,

I saw your comment during my vacation and didn't have a chance to answer yet.

We are currently gathering requirements for a new version of xarf. We will start adding some new type schemas to the development version of the xarf.

Can you provide more detailed information? What are the fields that you would want to see included.

If you want to help you can also open up a PR for that type. Otherwise we'll do so when we have enough info and time.
